// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeEventServiceServer is an autogenerated mock type for the UnsafeEventServiceServer type
type UnsafeEventServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedEventServiceServer provides a mock function with given fields:
func (_m *UnsafeEventServiceServer) mustEmbedUnimplementedEventServiceServer() {
	_m.Called()
}

type mockConstructorTestingTNewUnsafeEventServiceServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewUnsafeEventServiceServer creates a new instance of UnsafeEventServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUnsafeEventServiceServer(t mockConstructorTestingTNewUnsafeEventServiceServer) *UnsafeEventServiceServer {
	mock := &UnsafeEventServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
