// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	calendar "github.com/RomanSarvarov/otus_go_home_work/calendar"

	mock "github.com/stretchr/testify/mock"
)

// Broker is an autogenerated mock type for the Broker type
type Broker struct {
	mock.Mock
}

// ReadEventFromQueue provides a mock function with given fields: ctx
func (_m *Broker) ReadEventFromQueue(ctx context.Context) (*calendar.Event, error) {
	ret := _m.Called(ctx)

	var r0 *calendar.Event
	if rf, ok := ret.Get(0).(func(context.Context) *calendar.Event); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*calendar.Event)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewBroker interface {
	mock.TestingT
	Cleanup(func())
}

// NewBroker creates a new instance of Broker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBroker(t mockConstructorTestingTNewBroker) *Broker {
	mock := &Broker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
