// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	calendar "github.com/RomanSarvarov/otus_go_home_work/calendar"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// UpdateEvent provides a mock function with given fields: ctx, id, e
func (_m *Repository) UpdateEvent(ctx context.Context, id uuid.UUID, e *calendar.Event) (*calendar.Event, error) {
	ret := _m.Called(ctx, id, e)

	var r0 *calendar.Event
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *calendar.Event) *calendar.Event); ok {
		r0 = rf(ctx, id, e)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*calendar.Event)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *calendar.Event) error); ok {
		r1 = rf(ctx, id, e)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
